[versions]
compile-sdk = "34"
min-sdk = "26"
target-sdk = "34"
junit = "4.13.2"
junit-version = "1.1.5"
espresso-core = "3.5.1"
material = "1.10.0"


[libraries]
##########################################  系统库  ############################################################################
core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.12.0" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.6.1" }

##########################################  开发基础库  ############################################################################
cloud-api = { group = "io.github.cangHW", name = "Cloud-Api", version = "1.1.4.1" }
cloud-compiler = { group = "io.github.cangHW", name = "Cloud-Compiler", version = "1.1.4.1" }
cloud-plugin = { group = "io.github.cangHW", name = "Cloud-Plugin", version = "1.1.3.4" }
core-framework = {group = "io.github.cangHW", name="Service-CoreFramework", version="0.0.0.5"}
service-apihttp = {group = "io.github.cangHW", name="Service-Apihttp", version="0.0.0.5"}
service-threadpool = {group = "io.github.cangHW", name="Service-Threadpool", version="0.0.0.5"}
service-imageloader = {group = "io.github.cangHW", name="Service-Imageloader", version="0.0.0.5"}
service-webview = {group = "io.github.cangHW", name="Service-Webview", version="0.0.0.5"}
service-webview-bridge = {group = "io.github.cangHW", name="Service-WebBridge-Ds", version="0.0.0.4"}



##########################################  三方库  ############################################################################
# 日志库
log-timber = { group = "com.jakewharton.timber", name = "timber", version = "4.7.1" }

# 压缩库
file-zip = { group = "net.lingala.zip4j", name = "zip4j", version = "2.11.5" }

# json 解析库
json-gson = { module = "com.google.code.gson:gson", version = "2.10.1" }

# 类似 SharedPreferences, 高性能键值对存储库
sp-mmkv = { module = "com.tencent:mmkv", version = "1.2.11" }


[plugins]
android-application = { id = "com.android.application", version = "8.5.0" }
android-library = { id = "com.android.library", version = "8.5.0" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "1.9.10" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "1.9.10" }

